### ISSUE TITLE
[2.14.0] iOS build error

### ISSUE THREAD

**Issue by Bardiamist** [auth0/react-native-auth0#528]
Not building after update from 2.13.3 to 2.14.0

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/bardiamist/Library/Developer/Xcode/DerivedData/proj-gcfwctharjklzxamsqckslyxgkbd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/A0Auth0.build/Objects-normal/arm64/A0Auth0.o /Users/bardiamist/Documents/proj/proj-mobile/node_modules/react-native-auth0/ios/A0Auth0.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'A0Auth0' from project 'Pods')
(1 failure)
```

<details>
  <summary>Screenshot</summary>
  
<img width="1078" alt="Screenshot 2022-10-10 at 16 58 07" src="https://user-images.githubusercontent.com/22082342/194841624-4a56c227-f8c7-4b8d-a787-af0842c05787.png">
</details>

**Comment by poovamraj** [comment]
Hi @Bardiamist, Can you try cleaning your project and trying to build again.

This would mean you must delete the folder in which your `pods` and `node_modules` are installed and do `pod install` and `yarn install` again.

**Comment by Bardiamist** [comment]
Hi @poovamraj 

Not helped:
1. Remove: `node_modules`, `Pods`, `yarn.lock`, `Podfile.lock`
1. `yarn`
1. `pod install`
1. `Xcode` -> `Product` -> `Clean Build Folder`

**Comment by poovamraj** [comment]
@Bardiamist I am not able to reproduce this issue. Can you try and reproduce in this [sample repository](https://github.com/auth0-samples/auth0-react-native-sample/tree/update-rna-version).

The header file you mentioned is used for interop between Swift and ObjC code and it is autogenerated. That is why I assumed clean up should fix it :\

**Comment by Bardiamist** [comment]
Not reproducing on fresh project but still can't update my project. In my project I can't jump to `#import "A0Auth0-Swift.h"` maybe need to add something to my `Bridging-Header.h`

**Comment by poovamraj** [comment]
Hi @Bardiamist where you able to fix this by any chance or any success in creating a reproducible sample for us?

**Comment by Bardiamist** [comment]
No, waiting now for something

**Comment by SmartByt3r** [comment]
Hi! I have the same issue, with version 2.14.0

**Comment by shrekuu** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/3136026/195530317-eac67ff5-1f32-4583-8c16-cdc79ea82f4f.png">

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/3136026/195531631-635dccd8-96db-4fff-a404-2025e847701d.png">

It seems this file is not there.

**Comment by poovamraj** [comment]
Hi @shrekuu @SmartByt3r @Bardiamist Can you try the suggestion from this [Stackoverflow Thread](https://stackoverflow.com/questions/24062618/swift-to-objective-c-header-not-created-in-xcode-6). 

It asks for the "Defines Module" setting under "Packaging" of "Build Settings" to be set to `Yes`

**Comment by Bardiamist** [comment]
My target already has "Defines Module" "YES"
I tried to set "Defines Module" "YES" for the full project but not helped
A fresh project works and without it

**Comment by poovamraj** [comment]
Hi, @Bardiamist any progress on this issue? It would be great to have a reproducible environment. Can you try to use a build setup similar to the one which is causing the issue on the sample app and then update it to see if the issue is reproducible?

**Comment by Bardiamist** [comment]
@poovamraj Hello

>any progress on this issue?

No, I'm still use react-native-auth0 2.13.3

>It would be great to have a reproducible environment. Can you try to use a build setup similar to the one which is causing the issue on the sample app and then update it to see if the issue is reproducible?

Unfortunatelly my project is big and I have no idea what could be causing this problem

You can create branch based on 2.13.3 and checrry pick only related change and I can test this branch. Then we can locilize the problem.

**Comment by ebg1223** [comment]
Same issue here. @poovamraj  happy to help diagnose.

**Comment by poovamraj** [comment]
@ebg1223 can you provide a reproducible sample so that we can look into this?

**Comment by poovamraj** [comment]
@Bardiamist The changes related to this should be out of this commit [here](https://github.com/auth0/react-native-auth0/commit/6767e045fb5786342785e27828456c98db79d120)

**Comment by poovamraj** [comment]
@ebg1223 That's a great find! I'll check this one out and get the docs ready. @Bardiamist Can you verify this as well?

**Comment by ebg1223** [comment]
@poovamraj Thank you!! 

I wish i knew more about the expo native build process to give insight into the importance of this flag, or how to correct it on the native side, but I have seen this requirement in other libs besides firebase.

Maybe someone more knowledgeable in this aspect can suggest a fix to allow for useFrameworks:static to maintain compatibility with other libs.

**Comment by Bardiamist** [comment]
@poovamraj Hell, yes I'm use Firebase and it's [require](https://rnfirebase.io/#altering-cocoapods-to-use-frameworks) `use_frameworks!`

I use bare React native project so repro steps:
1. `npx react-native init AwesomeProject`
1. `yarn add react-native-auth0`
1. Add `use_frameworks! :linkage => :static` to `Podfile`
1. Don't forget to comment `:flipper_configuration => FlipperConfiguration.enabled` in `Podfile`
1. `cd ios/ && pod install`
1. `yarn ios`

Or you can clone this repro: https://github.com/Bardiamist/diff/tree/auth0-use-frameworks

**Comment by poovamraj** [comment]
Hey all 👋 I figured out what is causing the issue! So we are referencing the file from local context. So if you change the 

```
- #import "A0Auth0-Swift.h"
+ #import <A0Auth0/A0Auth0-Swift.h>
```

In A0Auth0.m in your node_modules, this should start working (There are tones of problems with Hermes and New architecture if you enable `use_frameworks` which is mentioned in Firebase docs itself)

Can someone verify this? I can try to figure out a patch.

**Comment by Bardiamist** [comment]
```
- #import "A0Auth0-Swift.h"
+ #import <A0Auth0/A0Auth0-Swift.h>
```
@poovamraj yes, it helped

>Hi all, does your app build if you add "${PODS_ROOT}/Headers/Public/A0Auth0" to the header search paths in the Xcode project?
@Widcket Tried to add it to `Library Search Paths` and `Runpatch Search Paths`: not helped

**Comment by Widcket** [comment]
@Bardiamist can you please try out the branch [feature/static-linking-support](https://github.com/auth0/react-native-auth0/pull/555)?

**Comment by Bardiamist** [comment]
Tried, it works
```
"react-native-auth0": "git+ssh://git@github.com/auth0/react-native-auth0.git#feature/static-linking-support",
```
