### ISSUE TITLE
Android hangs in RN 0.70.6

### ISSUE THREAD

**Issue by shawna-donnelly** [auth0/react-native-auth0#582]
### Describe the problem
Auth0 working properly for ios, but when I try to run it for android, it hangs after selecting my email address from the Google login. I am not seeing any kind of log other than TrafficStats with tagSocket(80) in LogCat. Otherwise, no feedback at all. 

### What was the expected behavior?
I expect the login to complete. 

### Reproduction

Started a new typescript project, which used 0.70.6. Used useAuth0 and added a provider. Updated manifest placeholders to use my auth0 domain. Ran project, and it is not working. Works properly in iOS. 

### Environment

"react": "18.1.0",
        "react-native": "0.70.6",
        "react-native-auth0": "^2.16.0",

- **Version of this library used:**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by shawna-donnelly** [comment]
Seems to work on the emulator. Not sure why it doesn't work on my physical device.

**Comment by poovamraj** [comment]
Can you share the device details? Also reproducing this on our [sample repository](https://github.com/auth0-samples/auth0-react-native-sample) would make it a lot easier to debug it.

**Comment by owentar** [comment]
We're having similar issue (probably the same). Will try to add more info.

We've created an expo app and we're trying to introduce `react-native-auth0` to authenticate our users. Following the steps described [here](https://auth0.com/docs/quickstart/native/react-native-expo/00-login).

With all that, we're simply trying to test it first displaying a login button (when the user is not logged in) and a logout button when it is logged in). Pretty much as shown in the [sample repository](https://github.com/auth0-samples/auth0-react-native-sample/blob/master/00-Login-Expo/App.js)

**This works fine in iOS but doesn't work on Android**. We added a `console.log` to inspect the `error` reported by the hook. We can see the following message: `{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}`.

NOTE: **sometimes seems to be able to login, but most of the times this is not the case and the error can be seen in the console**. Again, this is only happening on Android. iOS seems to be working fine.

Repo reproducing the issue: https://github.com/owentar/rn-auth0-expo-test

@shawna-donnelly please confirm this is the same issue or we need to create a separate one.

**Comment by poovamraj** [comment]
@owentar can you try to reproduce this it in this branch - https://github.com/auth0/react-native-auth0/tree/test/existing-task-redirection-issue?

You have to provide your "domain" and "client_id" in `A0Auth0Module.java` and test your flow

**Comment by owentar** [comment]
@poovamraj I tried to build the demo repo with the `react-native-auth0` dep pointing to the branch you specified (changing the `AUTH_CLIENT_ID`, `AUTH_DOMAIN` and `AUTH_SCHEMA` in the `A0Auth0Module.java`) but when I'm trying to run the application on my device seems there's an error with the generated APK (no errors are thrown during build time).

Then only log I can see is:

```
Invariant Violation: Module HMRClient is not a registered callable module (calling setup). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

Any ideas what could I try or missing on my setup? What am I doing wrong?

**Comment by poovamraj** [comment]
Hi @owentar I checked out the sample repository you shared and it worked for me in Android emulator running API level 33. Were you able to narrow this down to specific environment? Can you also try it with custom scheme?

About the issue you faced with Expo, I found [this](https://stackoverflow.com/questions/53220633/module-hmrclient-is-not-a-registered-callable-module-calling-enable-in-linux) checking for it online. Let me know if it helps

**Comment by poovamraj** [comment]
Hi @owentar @shawna-donnelly, any update on this issue?

**Comment by ericpeweh** [comment]
Is there any updates to this issue ? I'm facing the same issue mentioned by @owentar , here is the error flow:
- User open app
- User clicked on "Log in" button which trigger `authorize()`
- Then app is redirected to Auth0 page to sign up/log in
- When user click "Continue" (finished login), it redirect back to app
- User is prompted to choose between 2 app (same app, same name)
- User select one of them, which could result in 2 case:
* SUCCESS: User is logged in, `user` object is provided, `error` is null
* ERROR: User is not logged in, `user` object is null, `error` is `{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}`
- Both case occurs randomly, i'm not sure what is going on (but sometimes when we choose 1 of the 2 app, it always works flawlessly) which also mentioned by @owentar 

This end with a really bad user experience since user now have to click login button multiple times until it finally works.
Here also provided information about my project setup:
-  "expo": "~47.0.12",
-  "react-native": "0.70.5",
-  "react-native-auth0": "2.17.1",
I'm running expo managed project with development client (EAS build) run with `npx expo start --dev-client`. 
Tested both on Physical device and Emulator (Android only)

Looking forward for updates, Thanks.

**Comment by poovamraj** [comment]
@owentar @ericpeweh the easiest way to overcome this now is to use the [custom scheme](https://github.com/auth0/react-native-auth0#expo) option our plugin provides. We are looking in ways to fix this without a breaking change. Will update in this thread once we have more information

**Comment by ericpeweh** [comment]
Thanks for your confirmation, i fixed it by using custom scheme. Will look forward for the updates

**Comment by owentar** [comment]
Thanks @poovamraj. We can confirm your suggestion to overcome the issue works!

**Comment by waheedakhter** [comment]
The issue I am facing is that when the RedirectActivity starts AuthenticationActivity it creates new instance of AuthenticationActivity instead of using the existing AuthenticationActivity as a result the newly created instance of AuthenticationActivity finishes according to the logic in OnResume function but the previously created AuthenticationActivity stays there that was started with startActivityForResult and keeps waiting infinitely for the newIntent to setResult.
my project info:
"react-native": "0.70.5",
"react-native-auth0": "2.17.1",

**Comment by poovamraj** [comment]
@waheedakhter I have never faced such issue. Are facing this in an Expo application? Can you create a seperate issue for this and provide details and a screen recording of this to understand this easily?

**Comment by devalnor** [comment]
Same issue here with prompt `login`.
And it's worse when we use custom domains....

``` await authorize({ scope: 'openid profile email', prompt: 'login' })```

**Comment by poovamraj** [comment]
@devalnor the fix mentioned here doesn't work in your case?

**Comment by devalnor** [comment]
@poovamraj Nope, the `customScheme` fix is not working in my case.

**Comment by poovamraj** [comment]
@devalnor can you use this command and provide the results you get for your particular package `adb shell dumpsys package r`

If there are more than 1 redirection for RedirectActivity, the issue can be identified there.

**Comment by devalnor** [comment]
@poovamraj 
Here the dump:
[dump.txt](https://github.com/auth0/react-native-auth0/files/10958970/dump.txt)

**Comment by poovamraj** [comment]
@devalnor the scheme `com.mbrella.mbrella` is used in 2 places 

com.mbrella.mbrella:
        3a96fb1 com.mbrella.mbrella/.MainActivity
        5431c04 com.mbrella.mbrella/com.auth0.react.RedirectActivity
        
Meaning custom scheme is not used here. Using custom scheme should fix this issue

**Comment by devalnor** [comment]
@poovamraj 

I tried with various `scheme` and `customScheme` but unfortunately I still have the issue.
* I started from the expo sample adapted with our clientId and domain.
* I build a `development-simulator` with custom-client enabled

It's working on iOS simulator but not in Android emulator
Did I miss something somewhere?

**app.json**
```
{
  "expo": {
    "name": "auth0",
    "slug": "auth0",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "scheme": "mbrella-auth",
    "plugins": [
      [
        "react-native-auth0",
        {
          "domain": "https://login.dev.mbrella.io",
          "customScheme": "mbrella-auth"
        }
      ]
    ],
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "io.mbrella.dev.employee"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "io.mbrella.dev.employee"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "5a744b42-d185-44de-8e30-37a480d8125e"
      }
    }
  }
}
```
**App.js**
```
const onLogin = async () => {
    try {
      await authorize({scope: 'openid profile email', prompt: 'login'},  {
        customScheme: 'mbrella-auth',
      });
      const {accessToken} = await getCredentials();
      Alert.alert('AccessToken: ' + accessToken);
    } catch (e) {
      console.log(e);
    }
  };
  ```
  
  **adb shell dumpsys package r | grep mbrella**
  ```
      io.mbrella.dev.employee:
        6555405 io.mbrella.dev.employee/.MainActivity
        6555405 io.mbrella.dev.employee/.MainActivity
        dc60426 io.mbrella.dev.employee/expo.modules.devlauncher.launcher.DevLauncherActivity
        49ea614 io.mbrella.dev.employee/expo.modules.devmenu.DevMenuActivity
      mbrella-auth:
        6555405 io.mbrella.dev.employee/.MainActivity
        17d3b68 io.mbrella.dev.employee/com.auth0.react.RedirectActivity
        6555405 io.mbrella.dev.employee/.MainActivity
 ```

**Comment by poovamraj** [comment]
@devalnor Clearly .MainActivity is interfering. And it is not generated from Auth0 package as you can see.

**Comment by devalnor** [comment]
**Problem Fixed**
For those who will come across this discussion, here's my input:
Upon conducting a more extensive examination of the `AndroidManifest.xml` within the `.apk`, I discovered two errors I made:

* Avoid using a customScheme that shares the same name as the global scheme
* Refrain from including a scheme in the domain parameters

I recommend incorporating additional tests into this library to prevent such issues.

**Comment by poovamraj** [comment]
Hi all, we have made few changes to the documentation that will avoid the confusion. The PRs to the docs are here

https://github.com/auth0/react-native-auth0/pull/610
https://github.com/auth0-samples/auth0-react-native-sample/pull/113

Please feel free to provide your feedback there. Closing this issue in favour of the PRs. But feel free to comment here if you have more to add and we can reopen this issue.

**Comment by KMathisGit** [comment]
I am having the same issues as others here and have failed to get this working with your suggestions @poovamraj.

I am running RN 0.70.5 and react-native-auth0 2.17.1

I have implemented customScheme multiple times and fails everytime. IOS device works without issue, on my physical android device after successful login to auth0 it just sits on blank webpage and never redirects to my app. On emulator however I see this error message "auth0.custom.scheme" links are blocked.

Here are the results of adb shell dumpsys package r | grep custom.scheme

```
auth0.custom.scheme:
  44736e1 my.package.name.here/com.auth0.react.RedirectActivity
```

After thinking about this for a while, I must ask the question, are we sure that .RedirectActivity intent is being triggered and NOT .MainActivity? This would explain why nothing happens for me, and also why all expo users before using `customScheme` were experiencing duplicate applications in the "open with" dialog.

Please any thoughts or updates on this would be greatly appreciated, this is causing a huge mess for us.

**Comment by poovamraj** [comment]
Hi @KMathisGit can you show me how you call the `authorize` method?

**Comment by KMathisGit** [comment]
@poovamraj Hi, I managed to resolve the issue. It was a simple mistake on my part. I use expo and so I also use the react-native-auth0 plugin within my app.config for expo. My issue was in the logic that dynamically sets the customScheme value in this app.config file based on what environment I do a build for. So even though inside my app, I was using the correct customScheme (meaning the callback provided to auth0 was correct) the customScheme from app.config was incorrect - so the android intents were being built incorrectly.

**Comment by camchis** [comment]
Anyone have a fix for this? We are using `customScheme` which only has one intent registered. Not expo project and the `customScheme` does not clash with the applicationId. We are passing in the `customScheme` in the `authorize` call too.
