### ISSUE TITLE
No redirection back after success login

### ISSUE THREAD

**Issue by david-shiko** [auth0/react-native-auth0#914]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I explored the source code a bit and it looks like this function freezes:

https://github.com/auth0/react-native-auth0/blob/e1771491969934cc20dd3ed0e8beeb6c5cf70577/src/webauth/agent.ts#L56

So, resolve(credentials); is never called.

I see that this function:

https://github.com/auth0/react-native-auth0/blob/e1771491969934cc20dd3ed0e8beeb6c5cf70577/android/src/main/java/com/auth0/react/A0Auth0Module.java#L145

was working correctly, but the execution does not return back to the JavaScript code.

Please, check my point.

### Reproduction

Most basic case - just try to login via google and use `authorize` method.

Anyway I got the infinitr loading after pressing any login button.

![Screenshot from 2024-06-05 03-37-52](https://github.com/auth0/react-native-auth0/assets/27439358/dcb5df25-bf3c-4561-98f7-1f747eba42c5)

### react-native-auth0 version

"react-native-auth0": "^3.1.0",

### React Native version

"react-native": "0.74.1",

### Platform

Android

### Platform version(s)

Linux david-comp 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sigaits** [comment]
I'm having the same problem using authorize() from the useAuth0 hook. According to the event logs on the dashboard, the authentication is successful using either social media or user/pwd but the universal login never returns to the app on Android. No issues on iOS.

Expo: 51
react-native-auth0: 3.2.1

**Comment by philippe-architect** [comment]
I have the same issue

**Comment by philippe-architect** [comment]
Fixed my issue, turns out I was using `https://` in my domain url in `app.json` and when initialising the `Auth0Provider` but not including in my allowed redirect urls. Removing the `https://` fixed it.

**Comment by poovamraj** [comment]
@david-shiko @sigaits Apologies on getting back on this. Were you able to figure out this issue similar to @philippe-architect by fixing the Callback URLs? Most of the time mismatch in callback URLs can cause the app to not reopen. You can share the callback URL used in both the Auth0 dashboard and the configuration here to further debug this issue.

**Comment by anuragkaushik10** [comment]
Recently updated react-native-auth0 to version 4.0.0 from 2.17.1 and react-native from 0.71.2 to 0.74.

Now when I am trying to login to application using universal login, it is able to get login success log at auth0 logs. But in reality the login is not redirecting back to app.

Help is highly appreciated as it is blocking us for production deployment.

If you need any additional info please let me know.

**Comment by anuragkaushik10** [comment]
Its done thanks to https://github.com/auth0/react-native-auth0/issues/747#issuecomment-2439196254

**Comment by poovamraj** [comment]
@anuragkaushik10 the solution mentioned there is for multiple domains. Any chance you missed the `.auth0` towards the end in the placeholder like this

```
  android {
    defaultConfig {
     manifestPlaceholders = [auth0Domain: "tenant1.auth0.com", auth0Scheme: "${applicationId}.auth0"]
    }
  }
```

**Comment by anuragkaushik10** [comment]
@poovamraj 

Yes we were using multiple tenets, but the thing is in older version of auth0 it was working when I had the following in my app/build.gradle

```
defaultConfig {
     manifestPlaceholders = [auth0Domain: "tenant1.auth0.com", auth0Scheme: "${applicationId}.auth0"]
}
```

Now I have done the same configuration but in AndroidManifest.xml file, like defining intent for multiple tenets.


```
+     <activity
+       android:name="com.auth0.android.provider.RedirectActivity"
+       tools:node="replace"
+       android:exported="true">
+       <intent-filter>
+         <action android:name="android.intent.action.VIEW" />
+         <category android:name="android.intent.category.DEFAULT" />
+         <category android:name="android.intent.category.BROWSABLE" />
+         <data
+           android:host="tenant1.auth0.com"
+           android:pathPrefix="/android/${applicationId}/callback"
+           android:scheme="${applicationId}.auth0" />
+         <data
+           android:host="tenant2.auth0.com"
+           android:pathPrefix="/android/${applicationId}/callback"
+           android:scheme="${applicationId}.auth0" />
+       </intent-filter>
+     </activity>
```

**Comment by poovamraj** [comment]
Thanks for the clarification @anuragkaushik10 

---

@david-shiko since others in this thread have found solution, and you have another Github issue raised here on similar topic - https://github.com/auth0/react-native-auth0/issues/915

I will close down this thread and follow up on #915. Thanks!
